export EDITOR='vim'
export PATH="$PATH:$HOME/.bin"
export PATH="$PATH:/opt/local/bin"
export PATH="$PATH:$HOME/.local/.bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.nodenv/bin"
export PATH="$PATH:$HOME/.rbenv/bin"
export PATH="$PATH:$HOME/.emacs.d/bin"
export PATH="$HOME/.nodenv/shims:$PATH" # comes first to override node
export PATH="$HOME/.rbenv/shims:$PATH" # comes first to override ruby
export JQ_COLORS="1;30:0;31:0;32:0;35:0;33:1;35:1;35"
