#!/bin/bash

normal=$(tput sgr0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)

configs="${HOME}/PersonalConfigs"
tFile="${HOME}/.teardown_list.txt"

if [[ ! "$PWD" == "$configs" ]]; then
    cd "${configs}" || exit 1
fi


[[ -f "$tFile" ]] && "${configs}/_teardown"

touch "$tFile"

IFS='
' # prevent splitting on spaces

function mapFiles() {
  array_of_dirFiles="$(ls -A "$1")"

  for fileOnly in ${array_of_dirFiles}
  do
    dirFile="$1/$fileOnly"
    cleanFile=$(echo "$dirFile" | sed "s:^./::")

    if	[[ ! $dirFile =~ (README.md|.DS_Store|./.gitignore$|.sw.?$|^./.git$|^./_.*) ]]
    then
      if [[ -d $dirFile ]]; then
        if [[ -L "$HOME/$dirFile" ]]; then
          echo "  ${yellow}~${normal} d: $cleanFile "

        elif [[ -f $dirFile ]]; then
          echo "${red}dir to be linked: $cleanFile is a already file${normal} you'll need to remove this manually"

        elif [[  -d "$HOME/$dirFile" ]]; then
          mapFiles "$dirFile"

        else
          mkdir "$HOME/$cleanFile"  || exit 1
          echo "$HOME/$cleanFile" >> "${tFile}"
          mapFiles "$dirFile"

        fi

      elif [[ -f $dirFile ]]; then
        if [[  -L "$HOME/$cleanFile" ]]; then
          echo "  ${yellow}~${normal} f: $dirFile "

        elif [[  -f "$HOME/$dirFile" ]]; then
          echo "  ${red}✘${normal} f: $dirFile already exists, you'll need to remove this manually"

        else
          ln -s "$configs/$cleanFile" "$HOME/$cleanFile" || exit 1
          echo "  ${green}✓${normal} f: $dirFile "
          echo "$HOME/$cleanFile" >> "${tFile}"

        fi
      else
        echo "$dirFile is not valid"
        exit 1
      fi
    fi
  done
}

mapFiles "."

sort -ro "${tFile}" "${tFile}"
