SPACESHIP_VI_MODE_SHOW=true
SPACESHIP_VI_MODE_INSERT=""
SPACESHIP_VI_MODE_NORMAL="⭐ "
spaceship_vi_mode_enable

SPACESHIP_DIR_SHOW=true
# # GIT
SPACESHIP_GIT_STATUS_PREFIX=""
SPACESHIP_GIT_STATUS_SUFFIX=""
SPACESHIP_GIT_STATUS_COLOR="red"
SPACESHIP_GIT_STATUS_MODIFIED="!"

SPACESHIP_GIT_STATUS_UNTRACKED=" \xF0\x9F\x8D\x80 " # 🍀
SPACESHIP_GIT_STATUS_MODIFIED=" \xF0\x9F\x94\xA7 " # 🔧
SPACESHIP_GIT_STATUS_ADDED=" \xF0\x9F\x94\xAE " # 🔮
SPACESHIP_GIT_STATUS_STASHED=" \xF0\x9F\x8D\xAF " # 🍯
SPACESHIP_GIT_STATUS_DELETED=" \xE2\x9D\x8C " # ❌
SPACESHIP_GIT_STATUS_AHEAD=" \xF0\x9F\x9A\x80 " # 🚀
SPACESHIP_GIT_STATUS_BEHIND=" \xF0\x9F\x92\x94 " # 💔
#
SPACESHIP_DOCKER_SHOW=true
SPACESHIP_NODE_SHOW=true
SPACESHIP_RUBY_SHOW=true
SPACESHIP_ELIXIR_SHOW=true

SPACESHIP_HG_SHOW=false
SPACESHIP_XCODE_SHOW_LOCAL=false
SPACESHIP_HOST_SHOW=false
SPACESHIP_PACKAGE_SHOW=false # broken?
SPACESHIP_SWIFT_SHOW_LOCAL=false
SPACESHIP_GOLANG_SHOW=false
SPACESHIP_PHP_SHOW=false
SPACESHIP_RUST_SHOW=false
SPACESHIP_JULIA_SHOW=false
SPACESHIP_AWS_SHOW=false
SPACESHIP_VENV_SHOW=false
SPACESHIP_CONDA_SHOW=false
SPACESHIP_PYENV_SHOW=false
SPACESHIP_DOTNET_SHOW=false
SPACESHIP_EMBER_SHOW=false
SPACESHIP_KUBECONTEXT_SHOW=false
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_JOBS_SHOW="false"
SPACESHIP_EXIT_CODE_SHOW=false
