# Dotty configuration file
# Manually created from hardcoded configuration
#
# This file controls dotty's symlink management behavior.
# You can customize paths, excludes, and project settings here.

[global]
# Global exclusion patterns applied to all projects
excludes = [
    "**/_?*/**",       # Files/folders starting with underscore
    "**/.gitignore",   # Git ignore files
    "**/README.md"     # README files
]

[[project]]
name = "home"
origin = "~/PersonalConfigs/home"
target = "~"

[[project]]
name = "config"
origin = "~/PersonalConfigs/config"
target = "~/.config"

[[project]]
name = "claude"
origin = "~/PersonalConfigs/claude"
target = "~/.claude"
excludes = ["**/agents/**"]

[[project]]
name = "claude-agents"
origin = "~/PersonalConfigs/claude/agents"
target = "~/.claude/agents"
link_directory = true

[[project]]
name = "work"
origin = "~/workfiles/home"
target = "~"

[[project]]
name = "deals"
origin = "~/workfiles/work/app/deals-light-ui/_git"
target = "~/work/app/deals-light-ui/.git"
