[global]
# Global exclusion patterns applied to all projects
excludes = [
    "**/_?*/**",       # Files/folders starting with underscore
    "**/.gitignore",   # Git ignore files
    "**/README.md"     # README files
]

[[project]]
name = "test"
origin = "~/PersonalConfigs/config/dotty"
target = "~/dotty-test"
