start-at-login = false
# You can use it to add commands that run after login to macOS user session.
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []
# 'after-startup-command' is run after 'after-login-command'
after-startup-command = []
# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
accordion-padding = 30
# Possible values: tiles|accordion
# NOTE: probably want to control this per monitor, this is good for laptops
default-root-container-layout = 'accordion'

# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[exec.env-vars]
PATH = '${HOME}/.local/bin:/${HOME}/.bun/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = [{ monitor."DELL U3421WE" = 15}, 5]
inner.vertical   = [{ monitor."DELL U3421WE" = 15}, 5]
outer.left       = [{ monitor."DELL U3421WE" = 15}, 5]
outer.bottom     = [{ monitor."DELL U3421WE" = 15}, 5]
outer.top        = [{ monitor."DELL U3421WE" = 15}, 5]
outer.right      = [{ monitor."DELL U3421WE" = 15}, 5]


# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]
# All possible modifiers: cmd, alt, ctrl, shift
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands
cmd-h = [] # Disable "hide application"
cmd-m = [] # Disables "minimise application"
cmd-alt-h = [] # Disable "hide others"
# cmd-ctrl-f = [] # Disable "full screen"

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
cmd-ctrl-t = 'layout tiles horizontal'
cmd-ctrl-a = 'layout accordion horizontal'
cmd-ctrl-f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout, handy to pop out current frame

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
cmd-ctrl-h = 'focus --boundaries-action wrap-around-the-workspace left'
cmd-ctrl-j = 'focus --boundaries-action wrap-around-the-workspace down'
cmd-ctrl-k = 'focus --boundaries-action wrap-around-the-workspace up'
cmd-ctrl-l = 'focus --boundaries-action wrap-around-the-workspace right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
cmd-ctrl-minus = 'resize smart -50'
cmd-ctrl-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-ctrl-u = 'workspace 1'
cmd-ctrl-i = 'workspace 2'
cmd-ctrl-o = 'workspace 3'
cmd-ctrl-p = 'workspace 4'

cmd-ctrl-space = 'fullscreen'
cmd-ctrl-backspace= 'resize width 1000'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
cmd-ctrl-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
# alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
cmd-ctrl-semicolon = 'mode service'
cmd-ctrl-m = 'mode move'
cmd-ctrl-slash = 'exec-and-forget kindly'
# cmd-enter = 'exec-and-forget open -n /Applications/kitty.app'

[mode.service.binding]
r = ['reload-config', 'mode main']
esc = 'mode main'
shift-r = ['flatten-workspace-tree', 'mode main'] # reset layout
backspace = ['close-all-windows-but-current', 'mode main']

[mode.move.binding]
# See: https://nikitabobko.github.io/AeroSpace/commands#move
h = 'focus --boundaries-action wrap-around-the-workspace left'
j = 'focus --boundaries-action wrap-around-the-workspace down'
k = 'focus --boundaries-action wrap-around-the-workspace up'
l = 'focus --boundaries-action wrap-around-the-workspace right'

shift-h = 'move left'
shift-j = 'move down'
shift-k = 'move up'
shift-l = 'move right'

# I seem to always expect to be done after a join
ctrl-h = 'join-with left'
ctrl-j = 'join-with down'
ctrl-k = 'join-with up'
ctrl-l = 'join-with right'

u = ['move-node-to-workspace --focus-follows-window 1', 'mode main']
i = ['move-node-to-workspace --focus-follows-window 2', 'mode main']
o = ['move-node-to-workspace --focus-follows-window 3', 'mode main']
p = ['move-node-to-workspace --focus-follows-window 4', 'mode main']

cmd-u = 'move-node-to-workspace 1'
cmd-i = 'move-node-to-workspace 2'
cmd-o = 'move-node-to-workspace 3'
cmd-p = 'move-node-to-workspace 4'

left = 'resize width -50'
right = 'resize height +50'
up = 'resize height -50'
down = 'resize width +50'

# TODO: this is for work mac
space = ['resize width 1000', 'mode main']

esc = 'mode main'

# https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback
#####################################
# Main
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace 1'

#####################################
# Alt
[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = 'move-node-to-workspace 2'
[[on-window-detected]]
if.app-id = 'com.TickTick.task.mac'
run = 'move-node-to-workspace 2'
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = 'move-node-to-workspace 2'

#####################################
# Social
[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = '(Slack|Teams)'
run = 'move-node-to-workspace 3'

#####################################
# Media
[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'move-node-to-workspace 4'

# youtube music
[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.cinhimbnkkaeohfgghhklpknlkffjgod'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 4'
#####################################
# Misc
# [[on-window-detected]]
# if.app-name-regex-substring = 'Reminders'
# run = 'move-node-to-workspace 4'

# [[on-window-detected]] # Everything on 1
# if.app-name-regex-substring = '.'
# if.during-aerospace-startup = true

#####################################
# Tiles Floats

# TODO: annoyingly this goes mental as the emulator wants to resize itself too
# Android emulator

# [[on-window-detected]]
# if.window-title-regex-substring='Android Emulator'
# if.during-aerospace-startup = false #set it to false explicitly 
# run = 'layout tiling'  # The callback itself

#####################################
# Floats
[[on-window-detected]]
if.app-name-regex-substring = 'Simulator'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'

