start-at-login = true
# You can use it to add commands that run after login to macOS user session.
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
accordion-padding = 30
# Possible values: tiles|accordion
# NOTE: probably want to control this per monitor, this is good for laptops
default-root-container-layout = 'accordion'

automatically-unhide-macos-hidden-apps = true

# exec-on-workspace-change = ['/Users/adam.hall/.local/bin/on-ws-change.sh']

[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.main.binding]

# All possible modifiers: cmd, alt, ctrl, shift
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# disable macos stuff and find better replacements where possible
cmd-h = ['workspace k'] # Also Disables "hide application"
cmd-m = [] # Disables "minimise application"
cmd-alt-h = [] # Disable "hide others"
cmd-ctrl-f = [] # Disable "full screen"

# See: https://nikitabobko.github.io/AeroSpace/commands#layout

cmd-ctrl-left = 'focus --boundaries-action wrap-around-the-workspace left'
cmd-ctrl-down = 'focus --boundaries-action wrap-around-the-workspace down'
cmd-ctrl-up =   'focus --boundaries-action wrap-around-the-workspace up'
cmd-ctrl-right ='focus --boundaries-action wrap-around-the-workspace right'

cmd-ctrl-h = 'workspace h'
cmd-ctrl-j = 'workspace j'
cmd-ctrl-k = 'workspace k'
cmd-ctrl-l = 'workspace-back-and-forth'

cmd-ctrl-minus = 'resize smart -50'
cmd-ctrl-equal = 'resize smart +50'
cmd-ctrl-backspace= 'resize width 1000'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
cmd-ctrl-semicolon = 'mode workspace'
cmd-ctrl-space = 'mode space'
# cmd-ctrl-r = 'mode resize'
# cmd-ctrl-m = 'mode move'
# cmd-ctrl-s = 'mode split'

[mode.workspace.binding]
r = ['reload-config', 'mode main']
t = ['layout tiles horizontal', 'mode main']
a = ['layout accordion horizontal', 'mode main']
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout, handy to pop out current frame
esc = ['flatten-workspace-tree', 'mode main'] # reset layout
backspace = ['close-all-windows-but-current', 'mode main']

[mode.move.binding]
# See: https://nikitabobko.github.io/AeroSpace/commands#move

u = ['move-node-to-workspace --focus-follows-window 1', 'mode main']
i = ['move-node-to-workspace --focus-follows-window 2', 'mode main']
o = ['move-node-to-workspace --focus-follows-window 3', 'mode main']
p = ['move-node-to-workspace --focus-follows-window 4', 'mode main']

shift-u = ['move-node-to-workspace 1', 'mode main']
shift-i = ['move-node-to-workspace 2', 'mode main']
shift-o = ['move-node-to-workspace 3', 'mode main']
shift-p = ['move-node-to-workspace 4', 'mode main']

space = 'mode main'
esc = 'mode main'

[mode.split.binding]
# I seem to always expect to be done after a join
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']

space = 'mode main'
esc = 'mode main'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'

# TODO: this is for work mac
equal = ['resize width 1000', 'mode main']

space = 'mode main'
esc = 'mode main'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
[mode.space.binding]
space = ['fullscreen', 'mode main']
left = 'move left'
down = 'move down'
up = 'move up'
right = 'move right'

1 = ['workspace 1', 'mode main']
2 = ['workspace 2', 'mode main']
3 = ['workspace 3', 'mode main']
4 = ['workspace 4', 'mode main']
5 = ['workspace 5', 'mode main']
6 = ['workspace 6', 'mode main']
7 = ['workspace 7', 'mode main']
8 = ['workspace 8', 'mode main']
9 = ['workspace 9', 'mode main']
a = ['workspace a', 'mode main']
b = ['workspace b', 'mode main']
c = ['workspace c', 'mode main']
d = ['workspace d', 'mode main']
e = ['workspace e', 'mode main']
f = ['workspace f', 'mode main']
g = ['workspace g', 'mode main']
h = ['workspace h', 'mode main']
i = ['workspace i', 'mode main']
j = ['workspace j', 'mode main']
k = ['workspace k', 'mode main']
l = ['workspace l', 'mode main']
m = ['workspace m', 'mode main']
n = ['workspace n', 'mode main']
o = ['workspace o', 'mode main']
p = ['workspace p', 'mode main']
q = ['workspace q', 'mode main']
r = ['workspace r', 'mode main']
s = ['workspace s', 'mode main']
t = ['workspace t', 'mode main']
u = ['workspace u', 'mode main']
v = ['workspace v', 'mode main']
w = ['workspace w', 'mode main']
x = ['workspace x', 'mode main']
y = ['workspace y', 'mode main']
z = ['workspace z', 'mode main']

cmd-ctrl-1 = ['move-node-to-workspace 1' ]
cmd-ctrl-2 = ['move-node-to-workspace 2' ]
cmd-ctrl-3 = ['move-node-to-workspace 3' ]
cmd-ctrl-4 = ['move-node-to-workspace 4' ]
cmd-ctrl-5 = ['move-node-to-workspace 5' ]
cmd-ctrl-6 = ['move-node-to-workspace 6' ]
cmd-ctrl-7 = ['move-node-to-workspace 7' ]
cmd-ctrl-8 = ['move-node-to-workspace 8' ]
cmd-ctrl-9 = ['move-node-to-workspace 9' ]
cmd-ctrl-a = ['move-node-to-workspace a' ]
cmd-ctrl-b = ['move-node-to-workspace b' ]
cmd-ctrl-c = ['move-node-to-workspace c' ]
cmd-ctrl-d = ['move-node-to-workspace d' ]
cmd-ctrl-e = ['move-node-to-workspace e' ]
cmd-ctrl-f = ['move-node-to-workspace f' ]
cmd-ctrl-g = ['move-node-to-workspace g' ]
cmd-ctrl-h = ['move-node-to-workspace h' ]
cmd-ctrl-i = ['move-node-to-workspace i' ]
cmd-ctrl-j = ['move-node-to-workspace j' ]
cmd-ctrl-k = ['move-node-to-workspace k' ]
cmd-ctrl-l = ['move-node-to-workspace l' ]
cmd-ctrl-m = ['move-node-to-workspace m' ]
cmd-ctrl-n = ['move-node-to-workspace n' ]
cmd-ctrl-o = ['move-node-to-workspace o' ]
cmd-ctrl-p = ['move-node-to-workspace p' ]
cmd-ctrl-q = ['move-node-to-workspace q' ]
cmd-ctrl-r = ['move-node-to-workspace r' ]
cmd-ctrl-s = ['move-node-to-workspace s' ]
cmd-ctrl-t = ['move-node-to-workspace t' ]
cmd-ctrl-u = ['move-node-to-workspace u' ]
cmd-ctrl-v = ['move-node-to-workspace v' ]
cmd-ctrl-w = ['move-node-to-workspace w' ]
cmd-ctrl-x = ['move-node-to-workspace x' ]
cmd-ctrl-y = ['move-node-to-workspace y' ]
cmd-ctrl-z = ['move-node-to-workspace z' ]

cmd-1 = ['move-node-to-workspace --focus-follows-window 1', 'mode main']
cmd-2 = ['move-node-to-workspace --focus-follows-window 2', 'mode main']
cmd-3 = ['move-node-to-workspace --focus-follows-window 3', 'mode main']
cmd-4 = ['move-node-to-workspace --focus-follows-window 4', 'mode main']
cmd-5 = ['move-node-to-workspace --focus-follows-window 5', 'mode main']
cmd-6 = ['move-node-to-workspace --focus-follows-window 6', 'mode main']
cmd-7 = ['move-node-to-workspace --focus-follows-window 7', 'mode main']
cmd-8 = ['move-node-to-workspace --focus-follows-window 8', 'mode main']
cmd-9 = ['move-node-to-workspace --focus-follows-window 9', 'mode main']
cmd-a = ['move-node-to-workspace --focus-follows-window a', 'mode main']
cmd-b = ['move-node-to-workspace --focus-follows-window b', 'mode main']
cmd-c = ['move-node-to-workspace --focus-follows-window c', 'mode main']
cmd-d = ['move-node-to-workspace --focus-follows-window d', 'mode main']
cmd-e = ['move-node-to-workspace --focus-follows-window e', 'mode main']
cmd-f = ['move-node-to-workspace --focus-follows-window f', 'mode main']
cmd-g = ['move-node-to-workspace --focus-follows-window g', 'mode main']
cmd-h = ['move-node-to-workspace --focus-follows-window h', 'mode main']
cmd-i = ['move-node-to-workspace --focus-follows-window i', 'mode main']
cmd-j = ['move-node-to-workspace --focus-follows-window j', 'mode main']
cmd-k = ['move-node-to-workspace --focus-follows-window k', 'mode main']
cmd-l = ['move-node-to-workspace --focus-follows-window l', 'mode main']
cmd-m = ['move-node-to-workspace --focus-follows-window m', 'mode main']
cmd-n = ['move-node-to-workspace --focus-follows-window n', 'mode main']
cmd-o = ['move-node-to-workspace --focus-follows-window o', 'mode main']
cmd-p = ['move-node-to-workspace --focus-follows-window p', 'mode main']
cmd-q = ['move-node-to-workspace --focus-follows-window q', 'mode main']
cmd-r = ['move-node-to-workspace --focus-follows-window r', 'mode main']
cmd-s = ['move-node-to-workspace --focus-follows-window s', 'mode main']
cmd-t = ['move-node-to-workspace --focus-follows-window t', 'mode main']
cmd-u = ['move-node-to-workspace --focus-follows-window u', 'mode main']
cmd-v = ['move-node-to-workspace --focus-follows-window v', 'mode main']
cmd-w = ['move-node-to-workspace --focus-follows-window w', 'mode main']
cmd-x = ['move-node-to-workspace --focus-follows-window x', 'mode main']
cmd-y = ['move-node-to-workspace --focus-follows-window y', 'mode main']
cmd-z = ['move-node-to-workspace --focus-follows-window z', 'mode main']

# https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback
# - https://nikitabobko.github.io/AeroSpace/goodness#popular-apps-ids
# - `aerospace list-apps`
# - mdls -name kMDItemCFBundleIdentifier -r /Applications/App.app
#####################################
# MAIN

# Browser
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace j'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace j'

# Browser
[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace k'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace k'

[[on-window-detected]]
if.app-id = 'com.figma.Desktop'
run = 'move-node-to-workspace f'

#####################################
# Media
[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'move-node-to-workspace m'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace m'

# youtube music
[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.cinhimbnkkaeohfgghhklpknlkffjgod'
run = 'move-node-to-workspace m'

#####################################
# Social
[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace w'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace s'

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = 'move-node-to-workspace t'

#####################################
# Misc
# [[on-window-detected]]
# if.app-name-regex-substring = 'Reminders'
# run = 'move-node-to-workspace 4'

# [[on-window-detected]] # Everything on 1
# if.app-name-regex-substring = '.'
# if.during-aerospace-startup = true

#####################################
# Tiles Floats

# TODO: annoyingly this goes mental as the emulator wants to resize itself too
# Android emulator

# [[on-window-detected]]
# if.window-title-regex-substring='Android Emulator'
# if.during-aerospace-startup = false #set it to false explicitly 
# run = 'layout tiling'  # The callback itself

#####################################
# Floats
[[on-window-detected]]
if.app-name-regex-substring = 'Simulator'
run = 'layout floating'
[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'

