#!/bin/bash

# remove unused images:
# docker image prune -a --filter "until=24h" --force

# docker container prune --filter "until=24h" --force

# really aggressive way to clean everything
docker system prune

alert
