#!/usr/bin/env bash

INITIAL_QUERY=""
RG_PREFIX="rg --column --line-number --no-heading --hidden --color=always -g '!.git' --smart-case "
FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
  fzf --bind "change:reload:$RG_PREFIX {q} || true" \
      --ansi --disabled --query "$INITIAL_QUERY" \
      --height=50% --layout=reverse
