#!/bin/bash

npm i -g npm-merge-driver 
npm i -g eslint_d

npm i -g typescript
npm i -g typescript-language-server
npm i -g dockerfile-language-server-nodejs
npm i -g vscode-css-languageserver-bin
npm i -g vscode-html-languageserver-bin

