#!/bin/bash

# npm i -g babel-cli
npm i -g create-react-app 
npm i -g create-react-native-app 
npm i -g dockerfile-language-server-nodejs
# npm i -g eslint 
# npm i -g javascript-typescript-langserver
npm i -g typescript-language-server
npm i -g typescript
npm i -g npm-merge-driver 
npm i -g vscode-css-languageserver-bin
npm i -g vscode-html-languageserver-bin
npm i -g yarn 
# npm i -g fkill
# npm i -g vtop
