#!/usr/bin/env bash
set -euo pipefail

declare -r arg=${1:-}
if [[ $arg == "-h" || $arg == "--help" ]]; then
    echo "Log into an Osprey group by choosing from an interactive list" >&2
    exit 1
fi

# shellcheck disable=SC2155
declare -r g=$(osprey config targets --list-groups \
               | grep -v "Configured groups" | cut -c 3- \
               | fzf --tac --prompt "> osprey user login -g ")

if [[ -n "${g}" ]]; then
    osprey user login -g "${g}"
fi