#!/usr/bin/env bash

# update global PATH varible with it's current value in shell
# this allows programs like emacs and kitty to see everything in the PATH
# sometimes Alfred needs its cache reset after

sudo launchctl config user path "${PATH}"
