#!/bin/bash

branch="`git rev-parse --abbrev-ref HEAD`"

if [ "$branch" == "master" ]; then
  echo -e "\n$ERROR: do not use on 'master'\n"

elif [ "$branch" != "" ]; then
  git checkout master
  git fetch
  git reset --hard origin/master
  git checkout -b SQUASH
  git merge --squash "$branch"
  git commit
  git branch -D "$branch"
  git checkout -b "$branch"
  git push --force origin "$branch"
  git branch -D SQUASH
fi