#!/bin/bash
normal=$(tput sgr0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)

tFile="${HOME}/.teardown_list.txt"

[[ ! -f "${tFile}" ]] && exit 1

IFS='
' # prevent splitting on spaces

links="$(cat "${tFile}")"

function updateTxt {
    gsed -i "s:${1}::" "${tFile}"
}

for link in ${links}
do
    if [[ -f "$link" ]]; then
        if [[  -L "$link" ]]; then
            rm "$link" || exit 1
            echo "  ${green}✓${normal} removed: $link "
            updateTxt "${link}"
        else
            echo "  ${red}✘${normal} $link is not a link"
        fi

    elif [[ -d "$link" ]]; then
        if [ "$(find "$link" -mindepth 1 -print -quit 2>/dev/null)" ]; then
            echo "  ${yellow}~${normal} $link: dir not empty"
            updateTxt "${link}"

        else
            rm -r "$link" || exit 1
            echo "  ${green}✓${normal} removed: $link "
            updateTxt "${link}"

        fi
    else
        echo "  ${red}✘${normal} $link does not exist"

    fi
done

gsed -i "/^$/d" "${tFile}"
