command_timeout = 750

[aws]
symbol = "  "

[battery]
disabled = true

[buf]
symbol = " "

[c]
# really slow
disabled = true
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
# truncate_to_repo = false
truncation_length = 100

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
